package info.pppc.pcom.capability.com;

/**
 * The com command is an interface that all commands must provide.
 * 
 * @author Mac
 */
public interface ICOMCommand {

	/**
	 * This method will be called by the com bridge whenever the
	 * command is executed.
	 * 
	 * @throws Throwable A throwable generated by the command.
	 */
	public void run() throws Throwable;
	
}
